-- MySQL Script generated by MySQL Workbench
-- Sat May  8 11:26:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mbtSports
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mbtSports
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbtSports` DEFAULT CHARACTER SET utf8 ;
USE `mbtSports` ;

-- -----------------------------------------------------
-- Table `mbtSports`.`STUDENT_USER_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`STUDENT_USER_INFO` (
  `USERID` INT NOT NULL COMMENT 'e-mailをそのままIDとして使用することを想定',
  `USERNAME` VARCHAR(120) NOT NULL,
  `AGE` INT NOT NULL COMMENT '年齢。指導担当の専門によって分ける必要があるため。',
  `ADDRESS` VARCHAR(45) NULL COMMENT '必要なし今のところなし.',
  `SPORTS_MAIN` VARCHAR(45) NULL COMMENT 'どのようなスポーツがメインかを取得',
  `SPORTS_EXPERIENCE_TYPE` VARCHAR(45) NOT NULL COMMENT '分類表を作り、どの程度の習熟度かの情報を取得する',
  `SPORTS_NEEDS_TEACHING` VARCHAR(100) NOT NULL COMMENT '分類表を作成し、どのようなタイプの指導を求めるかのキーをカンマ区切りで記録する。\n専用アクセサーでアクセスをさせる（コーディング規約にて定める）',
  `SPORTS_SEX` VARCHAR(45) NOT NULL COMMENT '大会へのエントリーはどちらの性別で行うかを記録',
  `SPORTS_HABITAREA` VARCHAR(45) NULL COMMENT '指導受講可能エリア。文字列入力によって、検索かかるようにする？',
  `STUDENT_USER_INFOcol` VARCHAR(45) NULL,
  `LOGIN_INFO` INT NULL COMMENT 'firebaseにてログイン認証は設定するものの、いったんこちら側でも何かしら取得できるよう、カラム設置。',
  `RULE_AGREEMENT` VARCHAR(45) NOT NULL COMMENT '規約に同意していただけたかどうかを記録。DB上だけでなく別途出力する形で保存する必要あり。',
  `GOOD_LIST` VARCHAR(10000) NULL COMMENT 'いいねリスト。ユーザが増えたらここはお気に入り機能と分割。（場合によっては、純粋なユーザ情報とビジネス利用ユーザ情報TBLは分割する必要性あり。）',
  PRIMARY KEY (`USERID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`TEACHER_USER_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`TEACHER_USER_INFO` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`KV_TEACHING_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`KV_TEACHING_TYPE` (
  `TEACHING_TYPE_ID` CHAR(3) NOT NULL COMMENT '命名規約は以下。\n\nXYZ\n\nX...対面or非対面で[ 0 or 1 ]\nY...教える内容によって変更。後ほど記述。\nZ...連番。必要あれば。デフォルトは0。',
  `TEACHING_TYPE_NAME` VARCHAR(45) NOT NULL COMMENT '指導方法の名称',
  `TEACHING_TYPE_DESCRIPTION` VARCHAR(1000) NOT NULL COMMENT '指導方法の説明',
  PRIMARY KEY (`TEACHING_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`KV_EXPERIANCE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`KV_EXPERIANCE_TYPE` (
  `KV_EXPERIANCE_TYPE_ID` CHAR(3) NOT NULL COMMENT '習熟度合いに関する分類表ID。\n内容は汎用的に作り、どのような運動や活動（例：吹奏楽など）についても適用できるような内容とする。\n必要があれば、IDの裁判体系をうまく使い、活動ごとに分けるなどの対応を行う。\n\nXYZ\n\nX...活動種別。AtoZto1-0を用いて36種まで表記可能\nY...習熟レベル分類。AtoZto1-0を用いて36段階まで表記可能\nZ...バッファ。デフォルトは0とする。',
  `KV_EXPERIANCE_TYPE_NAME` VARCHAR(50) NOT NULL COMMENT '習熟内容の名前',
  `KV_EXPERIANCE_TYPE_DESCRIPTION` VARCHAR(500) NOT NULL COMMENT '習熟内容の説明。\nどのような習熟レベルであるかを記述する。',
  PRIMARY KEY (`KV_EXPERIANCE_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`TEACHING_CLASS_MASTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`TEACHING_CLASS_MASTER` (
  `ID` INT NOT NULL,
  `TEACHER_ID` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(200) NOT NULL,
  `DESCRIPTION` VARCHAR(1000) NOT NULL,
  `TEACHING_TYPE` VARCHAR(100) NOT NULL DEFAULT 'ハイフン区切りで持つ',
  `PLACE` VARCHAR(100) NOT NULL,
  `PRICE` VARCHAR(100) NULL,
  `MAX_SUBSCRIBER` INT NOT NULL,
  `MIN_SUBSCRIBER` INT NOT NULL,
  `INTRO_MEDIA_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `TEACHER_ID`),
  UNIQUE INDEX `INTRO_MEDIA_ID_UNIQUE` (`INTRO_MEDIA_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`TEACHING_CLASS_DETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`TEACHING_CLASS_DETAILS` (
  `CLASS_ID` INT NOT NULL,
  `PLAN_ID` INT NOT NULL,
  `DATE` VARCHAR(8) NULL,
  `START_TIME` VARCHAR(4) NULL,
  `END_TIME` VARCHAR(4) NULL,
  PRIMARY KEY (`CLASS_ID`, `PLAN_ID`),
  CONSTRAINT `CLASS_ID`
    FOREIGN KEY (`CLASS_ID`)
    REFERENCES `mbtSports`.`TEACHING_CLASS_MASTER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`SUBSCRIPTION_CLASSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`SUBSCRIPTION_CLASSES` (
  `CLASS_ID` INT NOT NULL,
  `DETAIL_ID` INT NOT NULL,
  `STUDENT_ID` INT NOT NULL,
  `MEMO` VARCHAR(400) NULL,
  `END_FLG` CHAR(1) NOT NULL DEFAULT '論理削除フラグ',
  `ACCOUNT_CHECK_STATUS` VARCHAR(2) NOT NULL DEFAULT '会計ステータス',
  PRIMARY KEY (`CLASS_ID`, `DETAIL_ID`, `STUDENT_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mbtSports`.`TEACHING_CLASS_MEDIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mbtSports`.`TEACHING_CLASS_MEDIA` (
  `CLASS_ID` INT NOT NULL,
  `MEDIA_ID` INT NOT NULL,
  `MEDIA` MEDIUMBLOB NOT NULL DEFAULT 動画、画像を想定,
  PRIMARY KEY (`CLASS_ID`, `MEDIA_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
